#!/bin/bash
# Links lama-impl against the project's patched 64-bit runtime instead of the
# one lamac bundles. The bundled runtime caps the GC extra-roots pool at 32,
# which overflows when the compiler builds large arrays/closures (e.g. makeEnv
# builds a 71-element array). runtime/x64/ is the same runtime with a bumped
# MAX_EXTRA_ROOTS_NUMBER. Object order among .o files does not matter (they are
# always fully linked); runtime.a must come last so it is pulled on demand.
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
# Link against the project's own stdlib (lama/stdlib), whose Ostap has the
# packrat-memoization optimisation (integer memo keys + flat position arrays).
# lamac's bundled stdlib keys memo tables by hashing parser closures, which is
# super-linear and makes the self-hosted compiler ~100x slower.
# Build it first: cd ../stdlib && LAMA="$PWD" make LAMAC="lamac -I <opam>/share/Lama/x64"
STDLIB="$DIR/../stdlib"
RUNTIME="$DIR/../../runtime/x64/runtime.a"

# Build the patched runtime if it has not been built yet.
if [ ! -f "$RUNTIME" ]; then
  make -C "$(dirname "$RUNTIME")"
fi

# Build the optimized stdlib objects if not present. lamac needs its own stdlib
# on the search path for Std.i (via -I); the checked-in .i are regenerated by
# the build, so restore them afterwards (lamac encodes infix anchors slightly
# differently, which the self-hosted compiler must read in its own form).
if ! ls "$STDLIB"/Ostap.o >/dev/null 2>&1; then
  OPAM_STDLIB="$(dirname "$(dirname "$(readlink -f "$(command -v lamac)")")")/share/Lama/x64"
  ( cd "$STDLIB" && LAMA="$PWD" make LAMAC="lamac -I $OPAM_STDLIB" )
  git -C "$STDLIB" checkout -- '*.i' 2>/dev/null || true
fi

# Units imported (transitively) by Driver that are not part of compilerSrc.
STD_UNITS="Timer Buffer STM Lazy Data Matcher Fun Array Ref Collection List Ostap"
STD_OBJS=()
for u in $STD_UNITS; do STD_OBJS+=("$STDLIB/$u.o"); done

# The compiler's own units (Driver excluded: its `main` lives in Driver.s, and
# a `-c`-built Driver.o would not contain it). Listed explicitly so unrelated
# .lama/.o files in the directory (e.g. test programs) are not linked in.
LOCAL_UNITS="Builtins Expr Infix Interface Lexer Manifest Parser SM SMOptimizer State World X86"
LOCAL_OBJS=()
for u in $LOCAL_UNITS; do LOCAL_OBJS+=("$DIR/$u.o"); done

gcc -Wa,--noexecstack -g -o "$DIR/lama-impl" \
    "$DIR/Driver.s" "${LOCAL_OBJS[@]}" "${STD_OBJS[@]}" "$RUNTIME"

echo "linked $DIR/lama-impl against $RUNTIME"
